version: '3'

services:
  backend:
    image: golang:1.22-alpine3.19
    volumes:
      - ./:/workspace/
    command: "go run cmd/app/main.go"
    working_dir: /workspace/
    ports:
      - 4501:4500
